[package]
name = "mahjong-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
clap = { version = "4.1.11", features = ["derive"] }
rand = "0.8.5"
rand_pcg = "0.3.1"
